### ISSUE TITLE
woher kommt die klasse karte-open?

### ISSUE THREAD

**Issue by TSchertenleib** [TSchertenleib/InCartas-App#1]
Hallo Joël

vielleicht kannst du mir helfen. Ich komme irgendwie nicht dahinter, woher du die klasse für karte-open hergenommen hast bzw wo dass du diese definierst. Ich frage mich deswegen, weil ich ja weitere klassen manipulieren möchte um so die animationen zu vervollständigen. sorry ich komm mir blöd vor aber checks wirklich gerade nicht...  

```
// - KARTEN -----------------------

.karten {
  padding-top: 78px;
  padding-left: 3%;
  position: relative;
  .medi {
    position: relative;
    float: left;
    width: 94px;
    margin: 24px 26px;
  }
  .exp-icon {
    margin-right: 5px;
    float: left;
    width: 19px;
  }
  .karte {

    width: 97%;
    height: 117px;
    background: $card-background;
    box-shadow: $box-shadow-cards;
    .tagBar {
      position: absolute;
      height: 117px;
      width: 2%;
    }
    .karte-gruen {
      .tagBar {
        background: $green;
      }
    }
    .karte-orange {
      .tagBar {
        background: $orange;
      }
    }
    .karte-red {
      .tagBar {
        background: $red;
      }
    }
    .name {
      margin-left: 140px;
      padding-top: 15px;
      margin-bottom: 0;
      margin-top: 10px;
      font-size: $karten-titel-size;
    }
    .tag {
      margin-left: 140px;
      margin-top: 2px;
      font-size: $karten-tag-size;
      font-family: $karten-font-family;
      font-weight: 300;
    }
    .exp-date {
      margin-left: 165px;
      font-family: $karten-font-family;
      font-weigth: $font-weight-expired;
      font-size: $font-size-small;
      line-height: 20px;
      .datum {
        margin-left: 20px;
      }
    }
    .expired {
      margin-left: 165px;
      font-size: $font-size-small;
      color: $red;
      line-height: 22px;
      font-weigth: $font-weight-expired;
    }
    &:last-child {
      margin-bottom: 67px;
    }

    // animation stuff

    @keyframes karte-open {
      from {
        height: 117px;
      }
      to {
        height: 600px;
      }
    }
    &.active {
      height: 600px;
      animation: karte-open 1s;
    }
  }
}
```

das code-fragment befindet sich

app/styles/_medikamente.scss

vielleicht muss ich ja einfach auch nach hause schlafen gehen.. bin ja auch noch ein bisschen krank.

liebe grüsse

Thomas

**Comment by TSchertenleib** [comment]
@256dpi Hoffe du kannst mir helfen

**Comment by TSchertenleib** [comment]
@256dpi  Bin gerade so richtig am krank werden :( ich muss glaube ich jetzt noch ein bisschen schlafen und sehen ob ich später die kraft habe noch weiter zu programmieren

**Comment by 256dpi** [comment]
'karte-open' is die keyframe animation, die mit der Klasse '.active' getriggert wird. Hier wird die Klasse hinzugefügt und entfernt: https://github.com/TSchertenleib/InCartas-App/blob/develop/app/controllers/medikamente.js

**Comment by TSchertenleib** [comment]
okey und wenn ich eine neue animation machen will, dann kann ich einfach eine keiframe animation hinzufügen und die mit der klasse active triggern

**Comment by 256dpi** [comment]
ja sollte gehen

**Comment by TSchertenleib** [comment]
ok jetzt hanis checkt.. äntli phu
danke gäll

**Comment by TSchertenleib** [comment]
mit dem medikamenteController und em ng-click chan ich ja abcheckä öb es element aktiv isch oder nöd und dänn je nach dem e klass ufsetzä. das isch aber nur innerhalb vo dem element gültig wo ich die controller etc aghängt han oder? weisch du öbs irgend e möglichkeit git dass ich die klass ng-class="medClass" bi ng-click ufs element class="karten" chan uf es element usserhalb schufle? zb de header?

```

<header class="header-medikamente" ng-controller="medikamenteController" ng-click="toggleMed()" ng-class="medClass">
    <h1>Medikamente</h1>
</header>

<div class="karten" ng-controller="kartenController">
    <div class="karte" ng-repeat="med in meds" ng-controller="medikamenteController" ng-click="toggleMed()" ng-class="medClass">
        <div class="karte-{{med.typ}}">
            <div class="tagBar" ng-class="medClass"></div>
            <img class="medi" ng-src="{{med.bild}}">
            <h2 class="name">{{med.name}}</h2>
            <p class="tag">{{med.tag}}</p>
            <img class="exp-icon" ng-src="{{med.icon}}" src="">
            <p class="expired">{{med.expab}}</p>
            <p class="exp-date">{{med.exp}}<span class="datum">{{med.datum}}</span></p>
        </div>
    </div>
</div>


```

**Comment by 256dpi** [comment]
Für das muesch wider data zwüsche de controllers share mit ehere "statische datebank". Lueg im Wiki under "Share State":
https://iadzhdk.atlassian.net/wiki/display/CP/Angular.js

**Comment by TSchertenleib** [comment]
@256dpi  hoi Joël, 

nomal danke viel mal nomal für dini hilf. du, ich hans jetzt ächt probiert und bin stundelang dra gsi aber ich kriegs eifach nöd hi. Ich glaub damit ichs zitlich no anekrieg mues ich langsam mit principle afange. ich hans mit verschiedene sache probiert, han au no versucht mit $rootScope in controller z injectä damit das i contoller überall verfüegbar isch oder mit services aber ich kriegs eifach nöd hi... bin grad zimli frustriert. chume au nöd ganz drus was du meinsch mit date inere statische datebank, gseh d verbinfig zu mim problem grad nöd. 

ich gaub was für s nöchste jahr würklich wichtig isch, isch dass d studänte gnueg zit bechömed sich mit em programmiere usenand z setzä. ich mein ich finds ja cool dass mir sälber chönd entscheide öb mirs wänd programmiere oder nöd aber dasmal isch s programmiere ächt z churz cho. will eso programmiereds am schluss eifach die wos eh scho chönd und für die andere isches zwenig ziit, zviel ufs mal. s chan nöd jedä angular i zwei täg, zumindest ich nöd, wo zwar sehr interessiert isch alles welä z programmiere aber eifach me zit brucht als öpper wo scho me erfahrig hät. ich han afangs au die tutorials versucht aber au für die hani zweinig zit gha. bin bi de videos bis öppe zu 4te cho und uf codecademy öppe bis id hälfti. d sach isch, dass es unter ois glaub einigi hät wo gern würdet die sache umsetzä wo sie sich vorgnah händ, ich bin ja au nöd de einzig wos so ergange isch. das isch eifach mega schad. ich mach susch jetzt ifach mal en principle prototyp und lueg dänn fals i no zit han no mit dra witerprogrammiere. wett halt nöd mit nüt dastah am zistig.

danke uf jedä fall

grüess

Thomas

**Comment by TSchertenleib** [comment]
@256dpi wow ich habs hingekriegt!!!!!

**Comment by 256dpi** [comment]
Nice!

Wollte grad zurückschreiben... ;)
